language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=sqlite

before_script:
  - composer install --no-interaction --prefer-source

script:
  - make cs
  - make test COVERAGE="--coverage-clover build/logs/clover.xml"

after_script:
  - ./vendor/bin/coveralls -v
